INSERT INTO users (username, email, password, profile_pic, cuisine, bio, created_at, updated_at)
VALUES 
('john_doe', 'john@example.com', 'password123', 'https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'American', 'Love cooking!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('jane_smith', 'jane@example.com', 'password123', 'https://plus.unsplash.com/premium_photo-1670282393309-70fd7f8eb1ef?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'American', 'Baking enthusiast.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mike_lee', 'mike@example.com', 'password123', 'https://img.freepik.com/free-photo/young-man-worried-expression_1194-1619.jpg?size=626&ext=jpg', 'French', 'Home cook with a passion for Italian cuisine.',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('emily_clark', 'emily@example.com', 'password123', 'https://img.freepik.com/free-photo/front-view-smiley-woman-with-earbuds_23-2148613052.jpg?size=626&ext=jpg', 'Italian', 'Vegan food blogger.',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('samuel_green', 'samuel@example.com', 'password123', 'https://img.freepik.com/premium-photo/portrait-young-man_1048944-24360939.jpg?size=626&ext=jpg','American', 'Grill master and BBQ enthusiast.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('olivia_jones', 'olivia@example.com', 'password123', 'https://img.freepik.com/free-photo/portrait-beautiful-smiling-model-dressed-summer-clothes-trendy-girl-posing-street-funny-positive-woman-having-fun_158538-6285.jpg?size=626&ext=jpg','Japanese', 'Dessert lover and cake decorator.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('liam_wilson', 'liam@example.com', 'password123', 'https://img.freepik.com/premium-photo/portrait-man-with-blonde-hair-relaxing-outdoors_251136-63979.jpg?size=626&ext=jpg', 'Professional chef specializing in French cuisine.', 'Mexican',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('jecki_seo', 'jecki@example.com', 'password123', 'https://plus.unsplash.com/premium_photo-1682095664848-014a0a2bfd8a?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'French','Food photographer and stylist.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('noah_martin', 'noah@example.com', 'password123', 'https://img.freepik.com/premium-photo/young-handsome-unshaven-guy-close-up-face-portrait-spring-field-background-with-green-grass_118478-241.jpg?size=626&ext=jpg','Korean' ,'Recipe developer and food writer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('isabella_brown', 'isabella@example.com', 'password123', 'https://img.freepik.com/premium-photo/happy-woman-front-information-board-train-station-looking-camera_201606-16327.jpg?size=626&ext=jpg&ga=GA1.1.1468915539.1720534080&semt=ais_hybrid', 'Italian', 'Healthy eating advocate.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);