INSERT INTO save_recipe (user_id, recipe_id, created_at)
VALUES 
(1, 2, CURRENT_TIMESTAMP),
(2, 1, CURRENT_TIMESTAMP),
(3, 4, CURRENT_TIMESTAMP),
(1, 5, CURRENT_TIMESTAMP),
(4, 3, CURRENT_TIMESTAMP),
(5, 6, CURRENT_TIMESTAMP),
(2, 7, CURRENT_TIMESTAMP),
(6, 8, CURRENT_TIMESTAMP),
(7, 9, CURRENT_TIMESTAMP),
(8, 10, CURRENT_TIMESTAMP),
(3, 1, CURRENT_TIMESTAMP),
(4, 2, CURRENT_TIMESTAMP),
(5, 3, CURRENT_TIMESTAMP),
(6, 4, CURRENT_TIMESTAMP),
(7, 5, CURRENT_TIMESTAMP),
(8, 6, CURRENT_TIMESTAMP),
(9, 7, CURRENT_TIMESTAMP);
