INSERT INTO comments (user_id, recipe_id, comment_text, created_at)
VALUES 
(1, 2, 'This cake is amazing!', CURRENT_TIMESTAMP),
(2, 1, 'Delicious pasta recipe!', CURRENT_TIMESTAMP),
(3, 4, 'Love this cocktail!', CURRENT_TIMESTAMP),
(1, 5, 'Perfect for game night.', CURRENT_TIMESTAMP),
(4, 3, 'So fresh and tasty!', CURRENT_TIMESTAMP),
(5, 6, 'Healthy and delicious.', CURRENT_TIMESTAMP),
(2, 7, 'Best pie I have ever had.', CURRENT_TIMESTAMP),
(6, 8, 'Perfect salad for summer.', CURRENT_TIMESTAMP),
(7, 9, 'Refreshing and easy to make.', CURRENT_TIMESTAMP),
(8, 10, 'Perfect dip for parties.', CURRENT_TIMESTAMP),
(3, 1, 'So creamy and rich.', CURRENT_TIMESTAMP),
(4, 2, 'Amazing flavors!', CURRENT_TIMESTAMP),
(5, 3, 'Light and refreshing.', CURRENT_TIMESTAMP),
(6, 4, 'A new favorite drink.', CURRENT_TIMESTAMP),
(7, 5, 'Best wings ever.', CURRENT_TIMESTAMP),
(8, 6, 'Quick and easy to make.', CURRENT_TIMESTAMP),
(9, 7, 'So comforting and delicious.', CURRENT_TIMESTAMP),
(10, 8, 'A crowd-pleaser.', CURRENT_TIMESTAMP),
(1, 9, 'Great for brunch.', CURRENT_TIMESTAMP),
(2, 10, 'Perfect for summer.', CURRENT_TIMESTAMP),
(3, 6, 'So flavorful.', CURRENT_TIMESTAMP),
(4, 5, 'Loved every bite.', CURRENT_TIMESTAMP),
(5, 4, 'Such a refreshing drink.', CURRENT_TIMESTAMP),
(6, 3, 'A classic favorite.', CURRENT_TIMESTAMP),
(7, 2, 'Easy to make and delicious.', CURRENT_TIMESTAMP),
(8, 1, 'A must-try!', CURRENT_TIMESTAMP),
(9, 4, 'Perfectly balanced flavors.', CURRENT_TIMESTAMP),
(10, 3, 'So moist and delicious.', CURRENT_TIMESTAMP),
(1, 8, 'Loved the fresh ingredients.', CURRENT_TIMESTAMP),
(2, 7, 'Such a fun recipe.', CURRENT_TIMESTAMP),
(3, 5, 'Perfect for parties.', CURRENT_TIMESTAMP),
(4, 6, 'A healthy and tasty meal.', CURRENT_TIMESTAMP),
(5, 11, 'Fantastic recipe!', CURRENT_TIMESTAMP),
(6, 12, 'Great texture and taste.', CURRENT_TIMESTAMP),
(7, 13, 'My family loved it.', CURRENT_TIMESTAMP),
(8, 14, 'Super easy to follow.', CURRENT_TIMESTAMP),
(9, 15, 'A delicious meal.', CURRENT_TIMESTAMP),
(10, 16, 'Would make again.', CURRENT_TIMESTAMP),
(1, 17, 'Full of flavor.', CURRENT_TIMESTAMP),
(2, 18, 'Perfect for dinner.', CURRENT_TIMESTAMP),
(3, 19, 'Absolutely delicious.', CURRENT_TIMESTAMP),
(4, 20, 'Highly recommend.', CURRENT_TIMESTAMP),
(5, 21, 'A unique twist.', CURRENT_TIMESTAMP),
(6, 22, 'Loved by all.', CURRENT_TIMESTAMP),
(7, 23, 'Quick and flavorful.', CURRENT_TIMESTAMP),
(8, 24, 'Very satisfying.', CURRENT_TIMESTAMP),
(9, 25, 'A tasty treat.', CURRENT_TIMESTAMP),
(10, 26, 'So refreshing.', CURRENT_TIMESTAMP),
(1, 27, 'Perfect for lunch.', CURRENT_TIMESTAMP),
(2, 28, 'Full of nutrients.', CURRENT_TIMESTAMP),
(3, 29, 'A new family favorite.', CURRENT_TIMESTAMP),
(4, 30, 'So easy to make.', CURRENT_TIMESTAMP),
(5, 31, 'Tastes amazing.', CURRENT_TIMESTAMP),
(6, 32, 'A real crowd-pleaser.', CURRENT_TIMESTAMP),
(7, 33, 'Perfectly cooked.', CURRENT_TIMESTAMP),
(8, 34, 'A delightful dish.', CURRENT_TIMESTAMP),
(9, 35, 'So delicious.', CURRENT_TIMESTAMP),
(10, 36, 'A perfect meal.', CURRENT_TIMESTAMP),
(1, 37, 'Bursting with flavor.', CURRENT_TIMESTAMP),
(2, 38, 'Easy to prepare.', CURRENT_TIMESTAMP),
(3, 39, 'Everyone loved it.', CURRENT_TIMESTAMP),
(4, 40, 'Perfectly seasoned.', CURRENT_TIMESTAMP),
(5, 41, 'Such a great recipe.', CURRENT_TIMESTAMP),
(6, 42, 'Very flavorful.', CURRENT_TIMESTAMP),
(7, 43, 'A healthy option.', CURRENT_TIMESTAMP),
(8, 44, 'So tasty.', CURRENT_TIMESTAMP),
(9, 45, 'Easy and delicious.', CURRENT_TIMESTAMP),
(10, 46, 'Loved every bite.', CURRENT_TIMESTAMP),
(1, 47, 'A new favorite.', CURRENT_TIMESTAMP),
(2, 48, 'So fresh.', CURRENT_TIMESTAMP),
(3, 49, 'Perfectly cooked.', CURRENT_TIMESTAMP),
(4, 50, 'Full of flavor.', CURRENT_TIMESTAMP),
(5, 51, 'Absolutely delicious.', CURRENT_TIMESTAMP),
(6, 52, 'Loved by all.', CURRENT_TIMESTAMP),
(7, 53, 'Very tasty.', CURRENT_TIMESTAMP),
(8, 54, 'Super easy.', CURRENT_TIMESTAMP),
(9, 55, 'So refreshing.', CURRENT_TIMESTAMP),
(10, 56, 'Great texture.', CURRENT_TIMESTAMP),
(1, 57, 'Bursting with flavor.', CURRENT_TIMESTAMP),
(2, 58, 'Perfect for any occasion.', CURRENT_TIMESTAMP),
(3, 59, 'A real treat.', CURRENT_TIMESTAMP),
(4, 60, 'Highly recommend.', CURRENT_TIMESTAMP),
(5, 61, 'Perfectly seasoned.', CURRENT_TIMESTAMP),
(6, 62, 'Very flavorful.', CURRENT_TIMESTAMP),
(7, 63, 'Full of nutrients.', CURRENT_TIMESTAMP),
(8, 64, 'So easy to make.', CURRENT_TIMESTAMP),
(9, 65, 'A delightful dish.', CURRENT_TIMESTAMP),
(10, 66, 'So delicious.', CURRENT_TIMESTAMP),
(1, 67, 'A perfect meal.', CURRENT_TIMESTAMP),
(2, 68, 'Bursting with flavor.', CURRENT_TIMESTAMP),
(3, 69, 'Easy to prepare.', CURRENT_TIMESTAMP),
(4, 70, 'Everyone loved it.', CURRENT_TIMESTAMP),
(5, 71, 'Perfectly seasoned.', CURRENT_TIMESTAMP),
(6, 72, 'Such a great recipe.', CURRENT_TIMESTAMP),
(7, 73, 'Very flavorful.', CURRENT_TIMESTAMP),
(8, 74, 'A healthy option.', CURRENT_TIMESTAMP),
(9, 75, 'So tasty.', CURRENT_TIMESTAMP),
(10, 76, 'Easy and delicious.', CURRENT_TIMESTAMP),
(1, 77, 'Loved every bite.', CURRENT_TIMESTAMP),
(2, 78, 'A new favorite.', CURRENT_TIMESTAMP),
(3, 79, 'So fresh.', CURRENT_TIMESTAMP),
(4, 80, 'Perfectly cooked.', CURRENT_TIMESTAMP),
(5, 81, 'Full of flavor.', CURRENT_TIMESTAMP),
(6, 82, 'Absolutely delicious.', CURRENT_TIMESTAMP),
(7, 83, 'Loved by all.', CURRENT_TIMESTAMP),
(8, 84, 'Very tasty.', CURRENT_TIMESTAMP),
(9, 85, 'Super easy.', CURRENT_TIMESTAMP),
(10, 86, 'So refreshing.', CURRENT_TIMESTAMP),
(1, 87, 'Great texture.', CURRENT_TIMESTAMP),
(2, 88, 'Bursting with flavor.', CURRENT_TIMESTAMP),
(3, 89, 'Perfect for any occasion.', CURRENT_TIMESTAMP),
(4, 90, 'A real treat.', CURRENT_TIMESTAMP),
(5, 91, 'Highly recommend.', CURRENT_TIMESTAMP),
(6, 92, 'Perfectly seasoned.', CURRENT_TIMESTAMP),
(7, 93, 'Very flavorful.', CURRENT_TIMESTAMP),
(8, 94, 'Full of nutrients.', CURRENT_TIMESTAMP),
(9, 95, 'So easy to make.', CURRENT_TIMESTAMP),
(10, 96, 'A delightful dish.', CURRENT_TIMESTAMP),
(1, 97, 'So delicious.', CURRENT_TIMESTAMP),
(2, 98, 'A perfect meal.', CURRENT_TIMESTAMP),
(3, 99, 'Bursting with flavor.', CURRENT_TIMESTAMP),
(4, 100, 'Easy to prepare.', CURRENT_TIMESTAMP),
(5, 101, 'Everyone loved it.', CURRENT_TIMESTAMP),
(6, 102, 'Perfectly seasoned.', CURRENT_TIMESTAMP),
(7, 103, 'Such a great recipe.', CURRENT_TIMESTAMP),
(8, 104, 'Very flavorful.', CURRENT_TIMESTAMP),
(9, 105, 'A healthy option.', CURRENT_TIMESTAMP),
(10, 106, 'So tasty.', CURRENT_TIMESTAMP),
(1, 107, 'Easy and delicious.', CURRENT_TIMESTAMP),
(2, 108, 'Loved every bite.', CURRENT_TIMESTAMP),
(3, 109, 'A new favorite.', CURRENT_TIMESTAMP),
(4, 110, 'So fresh.', CURRENT_TIMESTAMP),
(5, 111, 'Perfectly cooked.', CURRENT_TIMESTAMP),
(6, 112, 'Full of flavor.', CURRENT_TIMESTAMP),
(7, 113, 'Absolutely delicious.', CURRENT_TIMESTAMP),
(8, 114, 'Loved by all.', CURRENT_TIMESTAMP),
(9, 115, 'Very tasty.', CURRENT_TIMESTAMP),
(10, 116, 'Super easy.', CURRENT_TIMESTAMP),
(1, 117, 'So refreshing.', CURRENT_TIMESTAMP),
(2, 118, 'Great texture.', CURRENT_TIMESTAMP);