INSERT INTO comments (user_id, recipe_id, comment_text, created_at)
VALUES 
(1, 2, 'This cake is amazing!', CURRENT_TIMESTAMP),
(2, 1, 'Delicious pasta recipe!', CURRENT_TIMESTAMP),
(3, 4, 'Love this cocktail!', CURRENT_TIMESTAMP),
(1, 5, 'Perfect for game night.', CURRENT_TIMESTAMP),
(4, 3, 'So fresh and tasty!', CURRENT_TIMESTAMP),
(5, 6, 'Healthy and delicious.', CURRENT_TIMESTAMP),
(2, 7, 'Best pie I have ever had.', CURRENT_TIMESTAMP),
(6, 8, 'Perfect salad for summer.', CURRENT_TIMESTAMP),
(7, 9, 'Refreshing and easy to make.', CURRENT_TIMESTAMP),
(8, 10, 'Perfect dip for parties.', CURRENT_TIMESTAMP),
(3, 1, 'So creamy and rich.', CURRENT_TIMESTAMP),
(4, 2, 'Amazing flavors!', CURRENT_TIMESTAMP),
(5, 3, 'Light and refreshing.', CURRENT_TIMESTAMP),
(6, 4, 'A new favorite drink.', CURRENT_TIMESTAMP),
(7, 5, 'Best wings ever.', CURRENT_TIMESTAMP),
(8, 6, 'Quick and easy to make.', CURRENT_TIMESTAMP),
(9, 7, 'So comforting and delicious.', CURRENT_TIMESTAMP),
(10, 8, 'A crowd-pleaser.', CURRENT_TIMESTAMP),
(1, 9, 'Great for brunch.', CURRENT_TIMESTAMP),
(2, 10, 'Perfect for summer.', CURRENT_TIMESTAMP),
(3, 6, 'So flavorful.', CURRENT_TIMESTAMP),
(4, 5, 'Loved every bite.', CURRENT_TIMESTAMP),
(5, 4, 'Such a refreshing drink.', CURRENT_TIMESTAMP),
(6, 3, 'A classic favorite.', CURRENT_TIMESTAMP),
(7, 2, 'Easy to make and delicious.', CURRENT_TIMESTAMP),
(8, 1, 'A must-try!', CURRENT_TIMESTAMP),
(9, 4, 'Perfectly balanced flavors.', CURRENT_TIMESTAMP),
(10, 3, 'So moist and delicious.', CURRENT_TIMESTAMP),
(1, 8, 'Loved the fresh ingredients.', CURRENT_TIMESTAMP),
(2, 7, 'Such a fun recipe.', CURRENT_TIMESTAMP),
(3, 5, 'Perfect for parties.', CURRENT_TIMESTAMP),
(4, 6, 'A healthy and tasty meal.', CURRENT_TIMESTAMP);
